name: 'Mark stale issues'

#on: workflow_dispatch
on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 01:00 UTC

jobs:
  stale-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 'Mark stale issues'
        uses: actions/stale@v9
        with:
          days-before-issue-stale: 1
          days-before-close: -1
          stale-issue-label: 'lifecycle/stale'
          exempt-issue-labels: 'lifecycle/rotten'
          # Add a comment with 'stale-issue-message' option if needed.

      - name: 'Mark rotten issues'
        uses: actions/stale@v9
        with:
          days-before-issue-stale: 1
          days-before-close: -1
          stale-issue-label: 'lifecycle/rotten'
          only-labels: 'lifecycle/stale'
          labels-to-remove-when-stale: 'lifecycle/stale'
          # Add a comment with 'stale-issue-message' option if needed.

      - name: 'Close rotten issues'
        uses: actions/stale@v9
        with:
          days-before-stale: -1
          days-before-close: 1
          stale-issue-label: 'lifecycle/rotten'
          # Add a comment with 'close-issue-message' option if needed.

