name: 'Mark stale issues'

on: workflow_dispatch
#  schedule:
#    - cron: '0 1 * * *'  # Runs daily at 01:00 UTC

jobs:
  stale-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      # Mark issues as stale if they have not been updated for a certain period.
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 1
          days-before-close: -1
          stale-issue-label: 'lifecycle/stale'
          # Add a comment with 'stale-issue-message' option if needed.

      # Mark issues as rotten if they are stale for a certain period.
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 1
          days-before-close: -1
          stale-issue-label: 'lifecycle/rotten'
          only-labels: 'lifecycle/stale'
          labels-to-remove-when-stale: 'lifecycle/stale'
          # Add a comment with 'stale-issue-message' option if needed.

      # Close rotten issues after a certain period of inactivity.
      - uses: actions/stale@v9
        with:
          days-before-close: 1
          stale-issue-label: 'lifecycle/rotten'
          # Add a comment with 'close-issue-message' option if needed.

